### ISSUE TITLE
DDNS, router and wifi hotspot

### ISSUE THREAD

**Issue by instance-g** [bashrc/freedombone#38]
Just love what you are doing by "stratching your itch" on this project. I've yet to get a working system. Currently stuck by item 1 below. Three humble, plain user, suggestions which I simply cannot resist throwing into your very creative and pragmatic pathway:

1. Many routers including mine, I have just discovered, severely limit ddns service choice. Hence, I suggest integrating the Debian package inadyn which looks to me like a solution. The package lists support for FreeDNS and other similar services.

2. Integrate a software router. No big ask!

3. Enable the Freedombone device to be hooked up through a wifi hotspot and ethernet - post installation user choice.

Effectively, a portable device option for Freedombone. Yielding: increased ease of use; wider uptake; wider uses and a wider emerging Freedombox ecosystem

**Comment by bashrc** [comment]
Thanks for the tips. I'll definitely investigate inadyn because it would be nice to support more than just a single DDNS provider.

Freedombone on a portable device I think would be harder because typically ports still need to be forwarded from an internet router.

**Comment by bashrc** [comment]
I've not been able to use the current inadyn package, since it lacked support for SSL, but the configuration now uses the current version of inadyn from Github and installs from source code. Hopefully at some point in future a more recent version will be packaged so that Freedombone can move closer towards becoming a pure blend.
