### ISSUE TITLE
mariadb-server installer hangs

### ISSUE THREAD

**Issue by jreeve0805** [bashrc/freedombone#47]
The installation hangs infinitely when installing mariadb-server. Well if you consider 22 hours an infinite amount of time anyways =)

The issue is described here;

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773631

**Comment by bashrc** [comment]
When I reinstalled recently I didn't get that long hang. I was installing from a different Debian repo than usual though. Supposedly the issue has been fixed upstream, but maybe not propagated to all repos.

**Comment by jreeve0805** [comment]
The repo I am having trouble with is the Canadian repo.  	

ftp.ca.debian.org/debian/

What repo are you using Bob? I'd like to try it and see if the installer goes through. 

-John

**Comment by bashrc** [comment]
So far I've been using either the German or the UK repos. One thing I noticed which was mentioned earlier is that if during installation you get asked to overwrite /etc/debian_version it's probably better to say yes, otherwise presumably debian isn't sure what version it is and that might cause problems with package versions.

**Comment by jreeve0805** [comment]
In the past I had always choosen no when asked to over write /etc/debian_version. This time through I choose yes, and also choose the Germany 1 repo for the installer. The mariadb installer still hung!  Weird.

**Comment by bashrc** [comment]
Strange.
