### ISSUE TITLE
How about HumHub integration?

### ISSUE THREAD

**Issue by flixi** [bashrc/freedombone#62]
How about making it possible for Users to choose the actual social network and offer https://www.humhub.org/ as a choice?

**Comment by bashrc** [comment]
I didn't know of HumHub. I'll try it out. Probably eventually there will be a choice, because I'd like to include Diaspora when it's packaged for debian. Currently Hubzilla is easy to install, has good privacy controls via the zot protocol and seamless federation via magic auth such that the user doesn't need to care about logging in to different servers.
